### ISSUE TITLE
Please add decimal support

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/GeolocationForPhoneGap#1]
Please add decimal support to bring this widget in line with the updated GoogleMaps module/widget.

**Comment by Andries-Smit** [comment]
Close issue; was resolved a while ago
https://github.com/mendix/GeolocationForPhoneGap/commit/b4b24d5609b65eacd321e80d5b6428f86b210fca#diff-f51337367dafb05db3fbc0f5ac6f4a04R26
