### ISSUE TITLE
Show loader during action/disable button

### ISSUE THREAD

**Issue by jonathan-wrstbnd** [mendix/GeolocationForPhoneGap#7]
This is a great widget, however when using a microflow after the button press, it is awkward to the user that nothing happens while the GPS/microflow process happens.  In my testing this can take up to 4 seconds even with a very simple microflow.  I've attempted to add this myself in the widget unsuccessfully.

**Comment by Andries-Smit** [comment]
We made JavaScript Nanoflow action of this widget for Mendix 8. This way you do not need a widget and  you can fully control the actions before and after. https://appstore.home.mendix.com/link/app/109515/
